### ISSUE TITLE
False Positive 0001:doctype/present about file with PHP processing instruction

### ISSUE THREAD

**Issue by christianhujer** [wawandco/milo#38]
Given the following well-formed and valid XHTML 5.2 file

```
<!DOCTYPE html>
<?php ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>Milo Test</title>
</head>
<body>
    <h1>Milo Test</h1>
</body>
</html>
```

When running `milo review test.xhtml`, it reports a false positive with the following output:
```
pi.xhtml:3:1: doctype tag must be present in the document (0001:doctype/present)
```

**Comment by paganotoni** [comment]
Thanks for reporting this one. I think is related with the fact that we're checking that the doctype is next to the html tag. Will cover it soon.
