### ISSUE TITLE
False Positive 0018:attribute/double-quotes on file with attribute values in apostrophes

### ISSUE THREAD

**Issue by christianhujer** [wawandco/milo#41]
Given the following well-formed and valid XHTML 5.2 file
```
<!DOCTYPE html>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
<head>
<title>Hello, world!</title>
</head>
<body>
<h1>Hello, world!</h1>
</body>
</html>
```

When running `milo review` on that file, Milo reports a false positive `0018:attribute/double-quotes`:
```
hello.xhtml:2:1: attr-value-double-quotes: Attribute values must be in double quotes (0018:attribute/double-quotes)
hello.xhtml:2:1: attr-value-double-quotes: Attribute values must be in double quotes (0018:attribute/double-quotes)
```

**Comment by paganotoni** [comment]
This is by design, the double-quotes reviewer wants to ensure we use " for our tag attributes.

**Comment by christianhujer** [comment]
In that case the tool needs a clear distinction between:
* Violations of the relevant specifications (HTML, XML, SVG, etc)
* Violations of arbitrary decisions of the tool makers.

Using apostrophes instead of quotes for attributes is completely valid according to the specification and an arbitrary decision of the tool makers. The tool should not treat these two different things the same way.
