### ISSUE TITLE
False Positive 0015:tag/pair on auto-closed <iframe/>

### ISSUE THREAD

**Issue by christianhujer** [wawandco/milo#42]
Given the following well-formed and valid XHTML 5.2 file
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>Milo Test</title>
</head>
<body>
    <h1>Milo Test</h1>
    <p>
        This XHTML auto-closing <iframe src="src" width="40" height="30" />.
    </p>
</body>
</html>
```

Milo wrongly reports
```
false-positives/pair.xhtml:2:1: tag-pair: Tag must be paired (0015:tag/pair)
false-positives/pair.xhtml:6:1: tag-pair: Tag must be paired (0015:tag/pair)
false-positives/pair.xhtml:8:1: tag-pair: Tag must be paired (0015:tag/pair)
```

**Comment by christianhujer** [comment]
This also happens on auto-closed `<script/>`.

**Comment by paganotoni** [comment]
Hey @christianhujer 👋. Thanks for reporting this one. Unfortunately none of these 2 tags are intended to be self-closing, even tho most of the browsers will understand it that’s syntactically incorrect.

**Comment by paganotoni** [comment]
To be clear I’m not 100% sure about this but the list of void elements in the HTML5 spec does not include in frame or script. Do you have a reference that states that iframes and scripts are void ?

https://html.spec.whatwg.org/multipage/syntax.html#void-elements

**Comment by christianhujer** [comment]
What you are missing is that "not self-closing" relates to the HTML syntax of documents. As I clearly stated in the bug report, this is an XHTML file, which is HTML using the XML syntax. The element isn't self-closing, the tag denoting the element is the XML EmptyElementSyntax, it is closed explicitly by the `/>` at its end.

**Comment by paganotoni** [comment]
Yes. You're right on this one. To start we're focusing on the HTML syntax for HTML. Maybe later we can work on the XML syntax.
