### ISSUE TITLE
Bootstrap data-attributes 

### ISSUE THREAD

**Issue by Kevindm14** [wawandco/milo#62]
Encountered an error with bootstrap with Data attributes. It tells me that the attributes 'src' 'href' and 'data' must have a value, it has it and it does not detect it.

`'src', 'href', and 'data' attributes of must have a value (007:tag/src-empty)`

This is the error line:

`<button class="btn btn-info px-4" data-toggle="modal" data-target="#exampleModal">Add task</button>`

**Comment by larrymjordan** [comment]
@Kevindm14 that case is a good one, it should be fixed once this PR gets merged. https://github.com/wawandco/milo/pull/61
