### ISSUE TITLE
False-positive: Empty href

### ISSUE THREAD

**Issue by paganotoni** [wawandco/milo#66]
The following case reports empty href on the `a` element.

```html
<nav aria-label="breadcrumb">
    <ol class="breadcrumb pl-0">
      <li class="breadcrumb-item"><a href=" <%= companyEventsPath({housing_company_id: params["housing_company_id"]}) %>">Events</a></li>
    </ol>
  </nav>
```

**Comment by larrymjordan** [comment]
@paganotoni I forgot to link this issue to this PR https://github.com/wawandco/milo/pull/71. I think we can close it since it is covered in there.

**Comment by paganotoni** [comment]
Nice! Thanks @larrymjordan I think that ERB implementation in the tokenizer will let us sleep way better :D
