### ISSUE TITLE
Evolution: Accept a list of files in arguments

### ISSUE THREAD

**Issue by nvuillam** [wawandco/milo#76]
I'm considering the integration of milo in [Mega-Linter](https://nvuillam.github.io/mega-linter/), but to do that with better performances i would need to make calls with multiple files

Example:

```shell
milo some_folder/some_file1.html another_folder/another_files.html another_folder/another_files_2.html
```

is it possible to release a new milo version allowing that ?

Thanks :)

**Comment by paganotoni** [comment]
Hey @nvuillam 👋 I know this is more than a year after but we recently added the ability to pass multiple paths to the review command.
